// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: schema/protobuf/fasit.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Fasit_CreateTenant_FullMethodName           = "/Fasit/CreateTenant"
	Fasit_GetTenant_FullMethodName              = "/Fasit/GetTenant"
	Fasit_CreateEnvironment_FullMethodName      = "/Fasit/CreateEnvironment"
	Fasit_GetEnvironment_FullMethodName         = "/Fasit/GetEnvironment"
	Fasit_SetEnvironmentValue_FullMethodName    = "/Fasit/SetEnvironmentValue"
	Fasit_GetEnvironmentValue_FullMethodName    = "/Fasit/GetEnvironmentValue"
	Fasit_ListEnvironmentValues_FullMethodName  = "/Fasit/ListEnvironmentValues"
	Fasit_DeleteEnvironmentValue_FullMethodName = "/Fasit/DeleteEnvironmentValue"
	Fasit_UpdateEnvironment_FullMethodName      = "/Fasit/UpdateEnvironment"
)

// FasitClient is the client API for Fasit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FasitClient interface {
	CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*CreateTenantResponse, error)
	GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*GetTenantResponse, error)
	CreateEnvironment(ctx context.Context, in *CreateEnvironmentRequest, opts ...grpc.CallOption) (*CreateEnvironmentResponse, error)
	GetEnvironment(ctx context.Context, in *GetEnvironmentRequest, opts ...grpc.CallOption) (*GetEnvironmentResponse, error)
	SetEnvironmentValue(ctx context.Context, in *SetEnvironmentValueRequest, opts ...grpc.CallOption) (*SetEnvironmentValueResponse, error)
	GetEnvironmentValue(ctx context.Context, in *GetEnvironmentValueRequest, opts ...grpc.CallOption) (*GetEnvironmentValueResponse, error)
	ListEnvironmentValues(ctx context.Context, in *ListEnvironmentValuesRequest, opts ...grpc.CallOption) (*ListEnvironmentValuesResponse, error)
	DeleteEnvironmentValue(ctx context.Context, in *DeleteEnvironmentValueRequest, opts ...grpc.CallOption) (*DeleteEnvironmentValueResponse, error)
	UpdateEnvironment(ctx context.Context, in *UpdateEnvironmentRequest, opts ...grpc.CallOption) (*UpdateEnvironmentResponse, error)
}

type fasitClient struct {
	cc grpc.ClientConnInterface
}

func NewFasitClient(cc grpc.ClientConnInterface) FasitClient {
	return &fasitClient{cc}
}

func (c *fasitClient) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*CreateTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTenantResponse)
	err := c.cc.Invoke(ctx, Fasit_CreateTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fasitClient) GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*GetTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTenantResponse)
	err := c.cc.Invoke(ctx, Fasit_GetTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fasitClient) CreateEnvironment(ctx context.Context, in *CreateEnvironmentRequest, opts ...grpc.CallOption) (*CreateEnvironmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEnvironmentResponse)
	err := c.cc.Invoke(ctx, Fasit_CreateEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fasitClient) GetEnvironment(ctx context.Context, in *GetEnvironmentRequest, opts ...grpc.CallOption) (*GetEnvironmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEnvironmentResponse)
	err := c.cc.Invoke(ctx, Fasit_GetEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fasitClient) SetEnvironmentValue(ctx context.Context, in *SetEnvironmentValueRequest, opts ...grpc.CallOption) (*SetEnvironmentValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetEnvironmentValueResponse)
	err := c.cc.Invoke(ctx, Fasit_SetEnvironmentValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fasitClient) GetEnvironmentValue(ctx context.Context, in *GetEnvironmentValueRequest, opts ...grpc.CallOption) (*GetEnvironmentValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEnvironmentValueResponse)
	err := c.cc.Invoke(ctx, Fasit_GetEnvironmentValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fasitClient) ListEnvironmentValues(ctx context.Context, in *ListEnvironmentValuesRequest, opts ...grpc.CallOption) (*ListEnvironmentValuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnvironmentValuesResponse)
	err := c.cc.Invoke(ctx, Fasit_ListEnvironmentValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fasitClient) DeleteEnvironmentValue(ctx context.Context, in *DeleteEnvironmentValueRequest, opts ...grpc.CallOption) (*DeleteEnvironmentValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEnvironmentValueResponse)
	err := c.cc.Invoke(ctx, Fasit_DeleteEnvironmentValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fasitClient) UpdateEnvironment(ctx context.Context, in *UpdateEnvironmentRequest, opts ...grpc.CallOption) (*UpdateEnvironmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEnvironmentResponse)
	err := c.cc.Invoke(ctx, Fasit_UpdateEnvironment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FasitServer is the server API for Fasit service.
// All implementations must embed UnimplementedFasitServer
// for forward compatibility.
type FasitServer interface {
	CreateTenant(context.Context, *CreateTenantRequest) (*CreateTenantResponse, error)
	GetTenant(context.Context, *GetTenantRequest) (*GetTenantResponse, error)
	CreateEnvironment(context.Context, *CreateEnvironmentRequest) (*CreateEnvironmentResponse, error)
	GetEnvironment(context.Context, *GetEnvironmentRequest) (*GetEnvironmentResponse, error)
	SetEnvironmentValue(context.Context, *SetEnvironmentValueRequest) (*SetEnvironmentValueResponse, error)
	GetEnvironmentValue(context.Context, *GetEnvironmentValueRequest) (*GetEnvironmentValueResponse, error)
	ListEnvironmentValues(context.Context, *ListEnvironmentValuesRequest) (*ListEnvironmentValuesResponse, error)
	DeleteEnvironmentValue(context.Context, *DeleteEnvironmentValueRequest) (*DeleteEnvironmentValueResponse, error)
	UpdateEnvironment(context.Context, *UpdateEnvironmentRequest) (*UpdateEnvironmentResponse, error)
	mustEmbedUnimplementedFasitServer()
}

// UnimplementedFasitServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFasitServer struct{}

func (UnimplementedFasitServer) CreateTenant(context.Context, *CreateTenantRequest) (*CreateTenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTenant not implemented")
}
func (UnimplementedFasitServer) GetTenant(context.Context, *GetTenantRequest) (*GetTenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenant not implemented")
}
func (UnimplementedFasitServer) CreateEnvironment(context.Context, *CreateEnvironmentRequest) (*CreateEnvironmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEnvironment not implemented")
}
func (UnimplementedFasitServer) GetEnvironment(context.Context, *GetEnvironmentRequest) (*GetEnvironmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnvironment not implemented")
}
func (UnimplementedFasitServer) SetEnvironmentValue(context.Context, *SetEnvironmentValueRequest) (*SetEnvironmentValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEnvironmentValue not implemented")
}
func (UnimplementedFasitServer) GetEnvironmentValue(context.Context, *GetEnvironmentValueRequest) (*GetEnvironmentValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnvironmentValue not implemented")
}
func (UnimplementedFasitServer) ListEnvironmentValues(context.Context, *ListEnvironmentValuesRequest) (*ListEnvironmentValuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEnvironmentValues not implemented")
}
func (UnimplementedFasitServer) DeleteEnvironmentValue(context.Context, *DeleteEnvironmentValueRequest) (*DeleteEnvironmentValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEnvironmentValue not implemented")
}
func (UnimplementedFasitServer) UpdateEnvironment(context.Context, *UpdateEnvironmentRequest) (*UpdateEnvironmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEnvironment not implemented")
}
func (UnimplementedFasitServer) mustEmbedUnimplementedFasitServer() {}
func (UnimplementedFasitServer) testEmbeddedByValue()               {}

// UnsafeFasitServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FasitServer will
// result in compilation errors.
type UnsafeFasitServer interface {
	mustEmbedUnimplementedFasitServer()
}

func RegisterFasitServer(s grpc.ServiceRegistrar, srv FasitServer) {
	// If the following call pancis, it indicates UnimplementedFasitServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Fasit_ServiceDesc, srv)
}

func _Fasit_CreateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FasitServer).CreateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fasit_CreateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FasitServer).CreateTenant(ctx, req.(*CreateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fasit_GetTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FasitServer).GetTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fasit_GetTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FasitServer).GetTenant(ctx, req.(*GetTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fasit_CreateEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FasitServer).CreateEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fasit_CreateEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FasitServer).CreateEnvironment(ctx, req.(*CreateEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fasit_GetEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FasitServer).GetEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fasit_GetEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FasitServer).GetEnvironment(ctx, req.(*GetEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fasit_SetEnvironmentValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEnvironmentValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FasitServer).SetEnvironmentValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fasit_SetEnvironmentValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FasitServer).SetEnvironmentValue(ctx, req.(*SetEnvironmentValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fasit_GetEnvironmentValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnvironmentValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FasitServer).GetEnvironmentValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fasit_GetEnvironmentValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FasitServer).GetEnvironmentValue(ctx, req.(*GetEnvironmentValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fasit_ListEnvironmentValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnvironmentValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FasitServer).ListEnvironmentValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fasit_ListEnvironmentValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FasitServer).ListEnvironmentValues(ctx, req.(*ListEnvironmentValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fasit_DeleteEnvironmentValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEnvironmentValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FasitServer).DeleteEnvironmentValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fasit_DeleteEnvironmentValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FasitServer).DeleteEnvironmentValue(ctx, req.(*DeleteEnvironmentValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fasit_UpdateEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FasitServer).UpdateEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fasit_UpdateEnvironment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FasitServer).UpdateEnvironment(ctx, req.(*UpdateEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Fasit_ServiceDesc is the grpc.ServiceDesc for Fasit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fasit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Fasit",
	HandlerType: (*FasitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTenant",
			Handler:    _Fasit_CreateTenant_Handler,
		},
		{
			MethodName: "GetTenant",
			Handler:    _Fasit_GetTenant_Handler,
		},
		{
			MethodName: "CreateEnvironment",
			Handler:    _Fasit_CreateEnvironment_Handler,
		},
		{
			MethodName: "GetEnvironment",
			Handler:    _Fasit_GetEnvironment_Handler,
		},
		{
			MethodName: "SetEnvironmentValue",
			Handler:    _Fasit_SetEnvironmentValue_Handler,
		},
		{
			MethodName: "GetEnvironmentValue",
			Handler:    _Fasit_GetEnvironmentValue_Handler,
		},
		{
			MethodName: "ListEnvironmentValues",
			Handler:    _Fasit_ListEnvironmentValues_Handler,
		},
		{
			MethodName: "DeleteEnvironmentValue",
			Handler:    _Fasit_DeleteEnvironmentValue_Handler,
		},
		{
			MethodName: "UpdateEnvironment",
			Handler:    _Fasit_UpdateEnvironment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schema/protobuf/fasit.proto",
}
