// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: provider.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvironmentKind int32

const (
	EnvironmentKind_UNKNOWN    EnvironmentKind = 0
	EnvironmentKind_MANAGEMENT EnvironmentKind = 1
	EnvironmentKind_TENANT     EnvironmentKind = 2
	EnvironmentKind_ONPREM     EnvironmentKind = 3
	EnvironmentKind_LEGACY     EnvironmentKind = 4
)

// Enum value maps for EnvironmentKind.
var (
	EnvironmentKind_name = map[int32]string{
		0: "UNKNOWN",
		1: "MANAGEMENT",
		2: "TENANT",
		3: "ONPREM",
		4: "LEGACY",
	}
	EnvironmentKind_value = map[string]int32{
		"UNKNOWN":    0,
		"MANAGEMENT": 1,
		"TENANT":     2,
		"ONPREM":     3,
		"LEGACY":     4,
	}
)

func (x EnvironmentKind) Enum() *EnvironmentKind {
	p := new(EnvironmentKind)
	*p = x
	return p
}

func (x EnvironmentKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnvironmentKind) Descriptor() protoreflect.EnumDescriptor {
	return file_provider_proto_enumTypes[0].Descriptor()
}

func (EnvironmentKind) Type() protoreflect.EnumType {
	return &file_provider_proto_enumTypes[0]
}

func (x EnvironmentKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnvironmentKind.Descriptor instead.
func (EnvironmentKind) EnumDescriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{0}
}

type CreateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantRequest) Reset() {
	*x = GetTenantRequest{}
	mi := &file_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantRequest) ProtoMessage() {}

func (x *GetTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantRequest.ProtoReflect.Descriptor instead.
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{1}
}

func (x *GetTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantResponse) Reset() {
	*x = TenantResponse{}
	mi := &file_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantResponse) ProtoMessage() {}

func (x *TenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantResponse.ProtoReflect.Descriptor instead.
func (*TenantResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{2}
}

func (x *TenantResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TenantResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          EnvironmentKind        `protobuf:"varint,3,opt,name=kind,proto3,enum=EnvironmentKind" json:"kind,omitempty"`
	Labels        []*EnvironmentLabel    `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnvironmentRequest) Reset() {
	*x = CreateEnvironmentRequest{}
	mi := &file_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnvironmentRequest) ProtoMessage() {}

func (x *CreateEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*CreateEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEnvironmentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateEnvironmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEnvironmentRequest) GetKind() EnvironmentKind {
	if x != nil {
		return x.Kind
	}
	return EnvironmentKind_UNKNOWN
}

func (x *CreateEnvironmentRequest) GetLabels() []*EnvironmentLabel {
	if x != nil {
		return x.Labels
	}
	return nil
}

type UpdateEnvironmentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId    string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	Labels           []*EnvironmentLabel    `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	OidcIssuer       *string                `protobuf:"bytes,3,opt,name=oidc_issuer,json=oidcIssuer,proto3,oneof" json:"oidc_issuer,omitempty"`
	OidcDiscoveryUrl *string                `protobuf:"bytes,4,opt,name=oidc_discovery_url,json=oidcDiscoveryUrl,proto3,oneof" json:"oidc_discovery_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateEnvironmentRequest) Reset() {
	*x = UpdateEnvironmentRequest{}
	mi := &file_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnvironmentRequest) ProtoMessage() {}

func (x *UpdateEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateEnvironmentRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *UpdateEnvironmentRequest) GetLabels() []*EnvironmentLabel {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *UpdateEnvironmentRequest) GetOidcIssuer() string {
	if x != nil && x.OidcIssuer != nil {
		return *x.OidcIssuer
	}
	return ""
}

func (x *UpdateEnvironmentRequest) GetOidcDiscoveryUrl() string {
	if x != nil && x.OidcDiscoveryUrl != nil {
		return *x.OidcDiscoveryUrl
	}
	return ""
}

type EnvironmentLabel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentLabel) Reset() {
	*x = EnvironmentLabel{}
	mi := &file_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentLabel) ProtoMessage() {}

func (x *EnvironmentLabel) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentLabel.ProtoReflect.Descriptor instead.
func (*EnvironmentLabel) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{5}
}

func (x *EnvironmentLabel) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EnvironmentLabel) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetEnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvironmentRequest) Reset() {
	*x = GetEnvironmentRequest{}
	mi := &file_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvironmentRequest) ProtoMessage() {}

func (x *GetEnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvironmentRequest.ProtoReflect.Descriptor instead.
func (*GetEnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{6}
}

func (x *GetEnvironmentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetEnvironmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EnvironmentResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId         string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Labels           []*EnvironmentLabel    `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	OidcIssuer       string                 `protobuf:"bytes,5,opt,name=oidc_issuer,json=oidcIssuer,proto3" json:"oidc_issuer,omitempty"`
	OidcDiscoveryUrl string                 `protobuf:"bytes,6,opt,name=oidc_discovery_url,json=oidcDiscoveryUrl,proto3" json:"oidc_discovery_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EnvironmentResponse) Reset() {
	*x = EnvironmentResponse{}
	mi := &file_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentResponse) ProtoMessage() {}

func (x *EnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentResponse.ProtoReflect.Descriptor instead.
func (*EnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{7}
}

func (x *EnvironmentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EnvironmentResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EnvironmentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvironmentResponse) GetLabels() []*EnvironmentLabel {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *EnvironmentResponse) GetOidcIssuer() string {
	if x != nil {
		return x.OidcIssuer
	}
	return ""
}

func (x *EnvironmentResponse) GetOidcDiscoveryUrl() string {
	if x != nil {
		return x.OidcDiscoveryUrl
	}
	return ""
}

type CreateOrUpdateEnvironmentValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Secret        bool                   `protobuf:"varint,4,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateEnvironmentValueRequest) Reset() {
	*x = CreateOrUpdateEnvironmentValueRequest{}
	mi := &file_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateEnvironmentValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateEnvironmentValueRequest) ProtoMessage() {}

func (x *CreateOrUpdateEnvironmentValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateEnvironmentValueRequest.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateEnvironmentValueRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{8}
}

func (x *CreateOrUpdateEnvironmentValueRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *CreateOrUpdateEnvironmentValueRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateOrUpdateEnvironmentValueRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CreateOrUpdateEnvironmentValueRequest) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

type CreateOrUpdateEnvironmentValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrUpdateEnvironmentValueResponse) Reset() {
	*x = CreateOrUpdateEnvironmentValueResponse{}
	mi := &file_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrUpdateEnvironmentValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateEnvironmentValueResponse) ProtoMessage() {}

func (x *CreateOrUpdateEnvironmentValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateEnvironmentValueResponse.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateEnvironmentValueResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{9}
}

func (x *CreateOrUpdateEnvironmentValueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetEnvironmentValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvironmentValueRequest) Reset() {
	*x = GetEnvironmentValueRequest{}
	mi := &file_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvironmentValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvironmentValueRequest) ProtoMessage() {}

func (x *GetEnvironmentValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvironmentValueRequest.ProtoReflect.Descriptor instead.
func (*GetEnvironmentValueRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{10}
}

func (x *GetEnvironmentValueRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *GetEnvironmentValueRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type EnvironmentValueResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId   string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	Key             string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value           []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Secret          bool                   `protobuf:"varint,4,opt,name=secret,proto3" json:"secret,omitempty"`
	TenantId        string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	EnvironmentName string                 `protobuf:"bytes,6,opt,name=environment_name,json=environmentName,proto3" json:"environment_name,omitempty"`
	TenantName      string                 `protobuf:"bytes,7,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnvironmentValueResponse) Reset() {
	*x = EnvironmentValueResponse{}
	mi := &file_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentValueResponse) ProtoMessage() {}

func (x *EnvironmentValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentValueResponse.ProtoReflect.Descriptor instead.
func (*EnvironmentValueResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{11}
}

func (x *EnvironmentValueResponse) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *EnvironmentValueResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EnvironmentValueResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *EnvironmentValueResponse) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

func (x *EnvironmentValueResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EnvironmentValueResponse) GetEnvironmentName() string {
	if x != nil {
		return x.EnvironmentName
	}
	return ""
}

func (x *EnvironmentValueResponse) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

type GetEnvironmentValuesAcrossEnvsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnvironmentValuesAcrossEnvsRequest) Reset() {
	*x = GetEnvironmentValuesAcrossEnvsRequest{}
	mi := &file_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnvironmentValuesAcrossEnvsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnvironmentValuesAcrossEnvsRequest) ProtoMessage() {}

func (x *GetEnvironmentValuesAcrossEnvsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnvironmentValuesAcrossEnvsRequest.ProtoReflect.Descriptor instead.
func (*GetEnvironmentValuesAcrossEnvsRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{12}
}

func (x *GetEnvironmentValuesAcrossEnvsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type EnvironmentValuesAcrossEnvsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Values        []*EnvironmentValueResponse `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentValuesAcrossEnvsResponse) Reset() {
	*x = EnvironmentValuesAcrossEnvsResponse{}
	mi := &file_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentValuesAcrossEnvsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentValuesAcrossEnvsResponse) ProtoMessage() {}

func (x *EnvironmentValuesAcrossEnvsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentValuesAcrossEnvsResponse.ProtoReflect.Descriptor instead.
func (*EnvironmentValuesAcrossEnvsResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{13}
}

func (x *EnvironmentValuesAcrossEnvsResponse) GetValues() []*EnvironmentValueResponse {
	if x != nil {
		return x.Values
	}
	return nil
}

type DeleteEnvironmentValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEnvironmentValueRequest) Reset() {
	*x = DeleteEnvironmentValueRequest{}
	mi := &file_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEnvironmentValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEnvironmentValueRequest) ProtoMessage() {}

func (x *DeleteEnvironmentValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEnvironmentValueRequest.ProtoReflect.Descriptor instead.
func (*DeleteEnvironmentValueRequest) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteEnvironmentValueRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *DeleteEnvironmentValueRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteEnvironmentValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEnvironmentValueResponse) Reset() {
	*x = DeleteEnvironmentValueResponse{}
	mi := &file_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEnvironmentValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEnvironmentValueResponse) ProtoMessage() {}

func (x *DeleteEnvironmentValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEnvironmentValueResponse.ProtoReflect.Descriptor instead.
func (*DeleteEnvironmentValueResponse) Descriptor() ([]byte, []int) {
	return file_provider_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteEnvironmentValueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_provider_proto protoreflect.FileDescriptor

const file_provider_proto_rawDesc = "" +
	"\n" +
	"\x0eprovider.proto\")\n" +
	"\x13CreateTenantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\x10GetTenantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"4\n" +
	"\x0eTenantResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x9c\x01\n" +
	"\x18CreateEnvironmentRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x10.EnvironmentKindR\x04kind\x12)\n" +
	"\x06labels\x18\x04 \x03(\v2\x11.EnvironmentLabelR\x06labels\"\xec\x01\n" +
	"\x18UpdateEnvironmentRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12)\n" +
	"\x06labels\x18\x02 \x03(\v2\x11.EnvironmentLabelR\x06labels\x12$\n" +
	"\voidc_issuer\x18\x03 \x01(\tH\x00R\n" +
	"oidcIssuer\x88\x01\x01\x121\n" +
	"\x12oidc_discovery_url\x18\x04 \x01(\tH\x01R\x10oidcDiscoveryUrl\x88\x01\x01B\x0e\n" +
	"\f_oidc_issuerB\x15\n" +
	"\x13_oidc_discovery_url\":\n" +
	"\x10EnvironmentLabel\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"H\n" +
	"\x15GetEnvironmentRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xd0\x01\n" +
	"\x13EnvironmentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12)\n" +
	"\x06labels\x18\x04 \x03(\v2\x11.EnvironmentLabelR\x06labels\x12\x1f\n" +
	"\voidc_issuer\x18\x05 \x01(\tR\n" +
	"oidcIssuer\x12,\n" +
	"\x12oidc_discovery_url\x18\x06 \x01(\tR\x10oidcDiscoveryUrl\"\x8e\x01\n" +
	"%CreateOrUpdateEnvironmentValueRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x16\n" +
	"\x06secret\x18\x04 \x01(\bR\x06secret\"B\n" +
	"&CreateOrUpdateEnvironmentValueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"U\n" +
	"\x1aGetEnvironmentValueRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\xea\x01\n" +
	"\x18EnvironmentValueResponse\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x16\n" +
	"\x06secret\x18\x04 \x01(\bR\x06secret\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12)\n" +
	"\x10environment_name\x18\x06 \x01(\tR\x0fenvironmentName\x12\x1f\n" +
	"\vtenant_name\x18\a \x01(\tR\n" +
	"tenantName\"9\n" +
	"%GetEnvironmentValuesAcrossEnvsRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"X\n" +
	"#EnvironmentValuesAcrossEnvsResponse\x121\n" +
	"\x06values\x18\x01 \x03(\v2\x19.EnvironmentValueResponseR\x06values\"X\n" +
	"\x1dDeleteEnvironmentValueRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\":\n" +
	"\x1eDeleteEnvironmentValueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*R\n" +
	"\x0fEnvironmentKind\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"MANAGEMENT\x10\x01\x12\n" +
	"\n" +
	"\x06TENANT\x10\x02\x12\n" +
	"\n" +
	"\x06ONPREM\x10\x03\x12\n" +
	"\n" +
	"\x06LEGACY\x10\x042\xdd\x05\n" +
	"\bProvider\x127\n" +
	"\fCreateTenant\x12\x14.CreateTenantRequest\x1a\x0f.TenantResponse\"\x00\x121\n" +
	"\tGetTenant\x12\x11.GetTenantRequest\x1a\x0f.TenantResponse\"\x00\x12F\n" +
	"\x11CreateEnvironment\x12\x19.CreateEnvironmentRequest\x1a\x14.EnvironmentResponse\"\x00\x12@\n" +
	"\x0eGetEnvironment\x12\x16.GetEnvironmentRequest\x1a\x14.EnvironmentResponse\"\x00\x12s\n" +
	"\x1eCreateOrUpdateEnvironmentValue\x12&.CreateOrUpdateEnvironmentValueRequest\x1a'.CreateOrUpdateEnvironmentValueResponse\"\x00\x12O\n" +
	"\x13GetEnvironmentValue\x12\x1b.GetEnvironmentValueRequest\x1a\x19.EnvironmentValueResponse\"\x00\x12p\n" +
	"\x1eGetEnvironmentValuesAcrossEnvs\x12&.GetEnvironmentValuesAcrossEnvsRequest\x1a$.EnvironmentValuesAcrossEnvsResponse\"\x00\x12[\n" +
	"\x16DeleteEnvironmentValue\x12\x1e.DeleteEnvironmentValueRequest\x1a\x1f.DeleteEnvironmentValueResponse\"\x00\x12F\n" +
	"\x11UpdateEnvironment\x12\x19.UpdateEnvironmentRequest\x1a\x14.EnvironmentResponse\"\x00B%Z#internal/provider/protogen;protogenb\x06proto3"

var (
	file_provider_proto_rawDescOnce sync.Once
	file_provider_proto_rawDescData []byte
)

func file_provider_proto_rawDescGZIP() []byte {
	file_provider_proto_rawDescOnce.Do(func() {
		file_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_proto_rawDesc), len(file_provider_proto_rawDesc)))
	})
	return file_provider_proto_rawDescData
}

var file_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_provider_proto_goTypes = []any{
	(EnvironmentKind)(0),                           // 0: EnvironmentKind
	(*CreateTenantRequest)(nil),                    // 1: CreateTenantRequest
	(*GetTenantRequest)(nil),                       // 2: GetTenantRequest
	(*TenantResponse)(nil),                         // 3: TenantResponse
	(*CreateEnvironmentRequest)(nil),               // 4: CreateEnvironmentRequest
	(*UpdateEnvironmentRequest)(nil),               // 5: UpdateEnvironmentRequest
	(*EnvironmentLabel)(nil),                       // 6: EnvironmentLabel
	(*GetEnvironmentRequest)(nil),                  // 7: GetEnvironmentRequest
	(*EnvironmentResponse)(nil),                    // 8: EnvironmentResponse
	(*CreateOrUpdateEnvironmentValueRequest)(nil),  // 9: CreateOrUpdateEnvironmentValueRequest
	(*CreateOrUpdateEnvironmentValueResponse)(nil), // 10: CreateOrUpdateEnvironmentValueResponse
	(*GetEnvironmentValueRequest)(nil),             // 11: GetEnvironmentValueRequest
	(*EnvironmentValueResponse)(nil),               // 12: EnvironmentValueResponse
	(*GetEnvironmentValuesAcrossEnvsRequest)(nil),  // 13: GetEnvironmentValuesAcrossEnvsRequest
	(*EnvironmentValuesAcrossEnvsResponse)(nil),    // 14: EnvironmentValuesAcrossEnvsResponse
	(*DeleteEnvironmentValueRequest)(nil),          // 15: DeleteEnvironmentValueRequest
	(*DeleteEnvironmentValueResponse)(nil),         // 16: DeleteEnvironmentValueResponse
}
var file_provider_proto_depIdxs = []int32{
	0,  // 0: CreateEnvironmentRequest.kind:type_name -> EnvironmentKind
	6,  // 1: CreateEnvironmentRequest.labels:type_name -> EnvironmentLabel
	6,  // 2: UpdateEnvironmentRequest.labels:type_name -> EnvironmentLabel
	6,  // 3: EnvironmentResponse.labels:type_name -> EnvironmentLabel
	12, // 4: EnvironmentValuesAcrossEnvsResponse.values:type_name -> EnvironmentValueResponse
	1,  // 5: Provider.CreateTenant:input_type -> CreateTenantRequest
	2,  // 6: Provider.GetTenant:input_type -> GetTenantRequest
	4,  // 7: Provider.CreateEnvironment:input_type -> CreateEnvironmentRequest
	7,  // 8: Provider.GetEnvironment:input_type -> GetEnvironmentRequest
	9,  // 9: Provider.CreateOrUpdateEnvironmentValue:input_type -> CreateOrUpdateEnvironmentValueRequest
	11, // 10: Provider.GetEnvironmentValue:input_type -> GetEnvironmentValueRequest
	13, // 11: Provider.GetEnvironmentValuesAcrossEnvs:input_type -> GetEnvironmentValuesAcrossEnvsRequest
	15, // 12: Provider.DeleteEnvironmentValue:input_type -> DeleteEnvironmentValueRequest
	5,  // 13: Provider.UpdateEnvironment:input_type -> UpdateEnvironmentRequest
	3,  // 14: Provider.CreateTenant:output_type -> TenantResponse
	3,  // 15: Provider.GetTenant:output_type -> TenantResponse
	8,  // 16: Provider.CreateEnvironment:output_type -> EnvironmentResponse
	8,  // 17: Provider.GetEnvironment:output_type -> EnvironmentResponse
	10, // 18: Provider.CreateOrUpdateEnvironmentValue:output_type -> CreateOrUpdateEnvironmentValueResponse
	12, // 19: Provider.GetEnvironmentValue:output_type -> EnvironmentValueResponse
	14, // 20: Provider.GetEnvironmentValuesAcrossEnvs:output_type -> EnvironmentValuesAcrossEnvsResponse
	16, // 21: Provider.DeleteEnvironmentValue:output_type -> DeleteEnvironmentValueResponse
	8,  // 22: Provider.UpdateEnvironment:output_type -> EnvironmentResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_provider_proto_init() }
func file_provider_proto_init() {
	if File_provider_proto != nil {
		return
	}
	file_provider_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_proto_rawDesc), len(file_provider_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provider_proto_goTypes,
		DependencyIndexes: file_provider_proto_depIdxs,
		EnumInfos:         file_provider_proto_enumTypes,
		MessageInfos:      file_provider_proto_msgTypes,
	}.Build()
	File_provider_proto = out.File
	file_provider_proto_goTypes = nil
	file_provider_proto_depIdxs = nil
}
