version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gha:
        patterns:
          - '*'
    reviewers:
      - "@nais/core-dependabot-reviewers"      
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gomod:
        patterns:
          - '*'
    reviewers:
      - "@nais/core-dependabot-reviewers"      
